#ifndef ERROR_CODES_HH_
#define ERROR_CODES_HH_

typedef enum _retcodes
{
	RETRY= 1,
	SUCCESS= 0,
	ERROR= -1,
	ENCODER_NOT_SUPPORTED_ERROR= -2,
	VIDEO_ENCODER_NOT_SUPPORTED_ERROR= -3,
	AUDIO_ENCODER_NOT_SUPPORTED_ERROR= -4,
	STREAM_ALLOCATION_ERROR= -5,
	ADD_VIDEO_STREAM_ERROR= -6,
	ADD_AUDIO_STREAM_ERROR= -7,
	OPEN_VIDEO_CODEC_ERROR= -8,
	OPEN_AUDIO_CODEC_ERROR= -9,
	VIDEO_FRAME_BUFFER_ALLOC_ERROR= -10,
	AUDIO_SAMPLE_BUFFER_ALLOC_ERROR= -11,
	MUX_FORMAT_NOT_SUPPORTED= -12,
	OPEN_CONNECTION_OR_OFILE_ERRROR= -13,
	SENDING_DATA_OR_WRITING_ERROR= -14,
	VIDEO_FRAME_ENCODING_ERROR= -15,
	AUDIO_FRAME_ENCODING_ERROR= -16,
	INTERLEAVING_ERROR= -17,
	INTERLEAVING_BUF_OVERFLOW_ERROR= -18,
	JSON_COMMAND_PARSER_ERROR= -19,
	RTMP_CLIENT_ALREADY_INITIALIZED= -20,
	RTMP_CLIENT_NOT_PREV_INITIALIZED= -21,
	EMPTY_AUDIO_FRAME_ERROR= -22,
	VIDEO_RESOLUTION_OUT_OF_BOUNDS_ERROR= -23,
	ALREADY_IN_BACKGROUND_ERROR= -24,
	NOT_IN_BACKGROUND_ERROR= -25,
	BAD_ARGUMENT_OR_INITIALIZATION_ERROR= -26,
	NO_MULTIMEDIA_FOUND_IN_STREAM= -27,
	COULD_NOT_START_PLAYER= -28,
	PLAYER_DECODING_ERROR= -29,
	BAD_URL_PLAYER= -30,
	CONNECTION_RESET_ERROR= -31,
    // VideoRecorder related
    OPEN_CAMERA_ERROR= -32,
    SET_PREVIEW_DISPLAY_ERROR= -33,
    SET_CAMERA_PARAMS_ERROR= -34,
    OPEN_MIC_ERROR= -35,
    END_ERROR= -128, // Dummy
} _retcodes;

#endif /* ERROR_CODES_HH_ */